// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmOZZUQERnoGadEjJY8MCiuBRZNXnuEg',
    appId: '1:957964197223:web:247136238ed49deb7523c2',
    messagingSenderId: '957964197223',
    projectId: 'tabunganku-app-d1dea',
    authDomain: 'tabunganku-app-d1dea.firebaseapp.com',
    storageBucket: 'tabunganku-app-d1dea.firebasestorage.app',
    measurementId: 'G-JBVHZDB5XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKQTvN5dp4NUiE-Oy7dSqOhP_MkdtI24',
    appId: '1:957964197223:android:7f79545267cecb317523c2',
    messagingSenderId: '957964197223',
    projectId: 'tabunganku-app-d1dea',
    storageBucket: 'tabunganku-app-d1dea.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRgC10iNyXB898f0vVM6fcJonTZcLXM0',
    appId: '1:957964197223:ios:90266884353017817523c2',
    messagingSenderId: '957964197223',
    projectId: 'tabunganku-app-d1dea',
    storageBucket: 'tabunganku-app-d1dea.firebasestorage.app',
    iosBundleId: 'com.example.tabunganku',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkRgC10iNyXB898f0vVM6fcJonTZcLXM0',
    appId: '1:957964197223:ios:90266884353017817523c2',
    messagingSenderId: '957964197223',
    projectId: 'tabunganku-app-d1dea',
    storageBucket: 'tabunganku-app-d1dea.firebasestorage.app',
    iosBundleId: 'com.example.tabunganku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHmOZZUQERnoGadEjJY8MCiuBRZNXnuEg',
    appId: '1:957964197223:web:07705616871fae9d7523c2',
    messagingSenderId: '957964197223',
    projectId: 'tabunganku-app-d1dea',
    authDomain: 'tabunganku-app-d1dea.firebaseapp.com',
    storageBucket: 'tabunganku-app-d1dea.firebasestorage.app',
    measurementId: 'G-7H467PNXVB',
  );
}
